"""init

Revision ID: 3423af124b78
Revises:
Create Date: 2026-06-08 10:21:35.084711

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3423af124b78"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categorys",
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name_uz", sa.String(length=128), nullable=False),
        sa.Column("name_ru", sa.String(length=128), nullable=False),
        sa.Column("name_en", sa.String(length=128), nullable=False),
        sa.Column("icon", sa.String(length=64), nullable=True),
        sa.Column("parent_id", sa.BigInteger(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="1", nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["parent_id"], ["categorys.id"], name=op.f("fk_categorys_parent_id_categorys"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categorys")),
        sa.UniqueConstraint("slug", name="uq_categorys_slug"),
    )
    op.create_index(op.f("ix_categorys_created_at"), "categorys", ["created_at"], unique=False)
    op.create_index(op.f("ix_categorys_is_active"), "categorys", ["is_active"], unique=False)
    op.create_index(op.f("ix_categorys_parent_id"), "categorys", ["parent_id"], unique=False)
    op.create_index(op.f("ix_categorys_slug"), "categorys", ["slug"], unique=False)
    op.create_table(
        "citys",
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name_uz", sa.String(length=128), nullable=False),
        sa.Column("name_ru", sa.String(length=128), nullable=False),
        sa.Column("name_en", sa.String(length=128), nullable=False),
        sa.Column("region", sa.String(length=128), nullable=True),
        sa.Column("lat", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("lon", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_citys")),
        sa.UniqueConstraint("slug", name="uq_citys_slug"),
    )
    op.create_index(op.f("ix_citys_created_at"), "citys", ["created_at"], unique=False)
    op.create_index(op.f("ix_citys_is_active"), "citys", ["is_active"], unique=False)
    op.create_index(op.f("ix_citys_slug"), "citys", ["slug"], unique=False)
    op.create_table(
        "users",
        sa.Column("tg_id", sa.BigInteger(), nullable=False),
        sa.Column("tg_username", sa.String(length=64), nullable=True),
        sa.Column("tg_first_name", sa.String(length=128), nullable=True),
        sa.Column("tg_last_name", sa.String(length=128), nullable=True),
        sa.Column("tg_photo_url", sa.String(length=512), nullable=True),
        sa.Column("tg_language_code", sa.String(length=8), nullable=True),
        sa.Column("is_tg_premium", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("role", sa.Enum("CUSTOMER", "SELLER", "ADMIN", name="user_role", native_enum=False, length=20), server_default="customer", nullable=False),
        sa.Column("display_name", sa.String(length=128), nullable=True),
        sa.Column("locale", sa.Enum("UZ", "RU", "EN", name="locale", native_enum=False, length=4), server_default="uz", nullable=False),
        sa.Column("phone_hash", sa.String(length=64), nullable=True),
        sa.Column("city_id", sa.BigInteger(), nullable=True),
        sa.Column("is_blocked", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("marketing_opt_in", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["city_id"], ["citys.id"], name=op.f("fk_users_city_id_citys"), ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_city_id"), "users", ["city_id"], unique=False)
    op.create_index(op.f("ix_users_created_at"), "users", ["created_at"], unique=False)
    op.create_index(op.f("ix_users_is_deleted"), "users", ["is_deleted"], unique=False)
    op.create_index(op.f("ix_users_phone_hash"), "users", ["phone_hash"], unique=False)
    op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)
    op.create_index(op.f("ix_users_tg_id"), "users", ["tg_id"], unique=True)
    op.create_index(op.f("ix_users_tg_username"), "users", ["tg_username"], unique=False)
    op.create_table(
        "notifications",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("type", sa.Enum("ORDER_NEW", "ORDER_STATUS", "PAYMENT_PAID", "BROADCAST", "STORY_NEW", "COMMENT", "LIKE", "FOLLOW", "SYSTEM", name="notification_type", native_enum=False, length=24), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("body", sa.String(length=1024), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_notifications_user_id_users"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    op.create_index(op.f("ix_notifications_created_at"), "notifications", ["created_at"], unique=False)
    op.create_index(op.f("ix_notifications_read_at"), "notifications", ["read_at"], unique=False)
    op.create_index(op.f("ix_notifications_type"), "notifications", ["type"], unique=False)
    op.create_index(op.f("ix_notifications_user_id"), "notifications", ["user_id"], unique=False)
    op.create_table(
        "recipes",
        sa.Column("author_id", sa.BigInteger(), nullable=False),
        sa.Column("city_id", sa.BigInteger(), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("cover_url", sa.String(length=512), nullable=True),
        sa.Column("cook_time_min", sa.Integer(), nullable=True),
        sa.Column("servings", sa.Integer(), nullable=True),
        sa.Column("difficulty", sa.Enum("EASY", "MEDIUM", "HARD", name="difficulty_level", native_enum=False, length=10), server_default="easy", nullable=False),
        sa.Column("ingredients", sa.JSON(), nullable=False),
        sa.Column("steps", sa.JSON(), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("is_published", sa.Boolean(), server_default="1", nullable=False),
        sa.Column("likes_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("comments_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("saves_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], name=op.f("fk_recipes_author_id_users"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["city_id"], ["citys.id"], name=op.f("fk_recipes_city_id_citys"), ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recipes")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
        mysql_engine="InnoDB",
    )
    op.create_index("ftx_recipes_title_desc", "recipes", ["title", "description"], unique=False, mysql_prefix="FULLTEXT")
    op.create_index(op.f("ix_recipes_author_id"), "recipes", ["author_id"], unique=False)
    op.create_index(op.f("ix_recipes_city_id"), "recipes", ["city_id"], unique=False)
    op.create_index(op.f("ix_recipes_created_at"), "recipes", ["created_at"], unique=False)
    op.create_index(op.f("ix_recipes_is_deleted"), "recipes", ["is_deleted"], unique=False)
    op.create_index(op.f("ix_recipes_is_published"), "recipes", ["is_published"], unique=False)
    op.create_index("ix_recipes_pub_city", "recipes", ["is_published", "city_id"], unique=False)
    op.create_table(
        "seller_profiles",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("brand_name", sa.String(length=128), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("avatar_url", sa.String(length=512), nullable=True),
        sa.Column("cover_url", sa.String(length=512), nullable=True),
        sa.Column("contact_phone_e164", sa.String(length=20), nullable=True),
        sa.Column("contact_tg_username", sa.String(length=64), nullable=True),
        sa.Column("delivery_info", sa.Text(), nullable=True),
        sa.Column("city_id", sa.BigInteger(), nullable=True),
        sa.Column("address_hint", sa.String(length=256), nullable=True),
        sa.Column("lat", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("lon", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("verification", sa.Enum("UNVERIFIED", "PENDING", "VERIFIED", "REJECTED", name="seller_verification", native_enum=False, length=20), server_default="unverified", nullable=False),
        sa.Column("rating_avg", sa.Numeric(precision=3, scale=2), server_default="0", nullable=False),
        sa.Column("reviews_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("products_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("followers_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("orders_completed", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["city_id"], ["citys.id"], name=op.f("fk_seller_profiles_city_id_citys"), ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_seller_profiles_user_id_users"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_seller_profiles")),
    )
    op.create_index(op.f("ix_seller_profiles_brand_name"), "seller_profiles", ["brand_name"], unique=False)
    op.create_index(op.f("ix_seller_profiles_city_id"), "seller_profiles", ["city_id"], unique=False)
    op.create_index(op.f("ix_seller_profiles_created_at"), "seller_profiles", ["created_at"], unique=False)
    op.create_index(op.f("ix_seller_profiles_slug"), "seller_profiles", ["slug"], unique=True)
    op.create_index(op.f("ix_seller_profiles_user_id"), "seller_profiles", ["user_id"], unique=True)
    op.create_index(op.f("ix_seller_profiles_verification"), "seller_profiles", ["verification"], unique=False)
    op.create_table(
        "follows",
        sa.Column("follower_id", sa.BigInteger(), nullable=False),
        sa.Column("seller_id", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["follower_id"], ["users.id"], name=op.f("fk_follows_follower_id_users"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["seller_id"], ["seller_profiles.id"], name=op.f("fk_follows_seller_id_seller_profiles"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_follows")),
        sa.UniqueConstraint("follower_id", "seller_id", name="uq_follows_follower_id_seller_id"),
    )
    op.create_index(op.f("ix_follows_created_at"), "follows", ["created_at"], unique=False)
    op.create_index(op.f("ix_follows_follower_id"), "follows", ["follower_id"], unique=False)
    op.create_index(op.f("ix_follows_seller_id"), "follows", ["seller_id"], unique=False)
    op.create_table(
        "products",
        sa.Column("seller_id", sa.BigInteger(), nullable=False),
        sa.Column("category_id", sa.BigInteger(), nullable=True),
        sa.Column("city_id", sa.BigInteger(), nullable=True),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("price_minor", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("currency", sa.Enum("UZS", "USD", name="currency", native_enum=False, length=8), server_default="UZS", nullable=False),
        sa.Column("prep_time_hours", sa.Integer(), nullable=True),
        sa.Column("min_order_qty", sa.Integer(), server_default="1", nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("attributes", sa.JSON(), nullable=False),
        sa.Column("status", sa.Enum("DRAFT", "PUBLISHED", "ARCHIVED", "BLOCKED", name="product_status", native_enum=False, length=20), server_default="draft", nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("views_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("orders_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("likes_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["category_id"], ["categorys.id"], name=op.f("fk_products_category_id_categorys"), ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["city_id"], ["citys.id"], name=op.f("fk_products_city_id_citys"), ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["seller_id"], ["seller_profiles.id"], name=op.f("fk_products_seller_id_seller_profiles"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
        mysql_engine="InnoDB",
    )
    op.create_index("ftx_products_title_desc", "products", ["title", "description"], unique=False, mysql_prefix="FULLTEXT")
    op.create_index(op.f("ix_products_category_id"), "products", ["category_id"], unique=False)
    op.create_index(op.f("ix_products_city_id"), "products", ["city_id"], unique=False)
    op.create_index("ix_products_city_status_pub", "products", ["city_id", "status", "published_at"], unique=False)
    op.create_index(op.f("ix_products_created_at"), "products", ["created_at"], unique=False)
    op.create_index(op.f("ix_products_is_deleted"), "products", ["is_deleted"], unique=False)
    op.create_index(op.f("ix_products_published_at"), "products", ["published_at"], unique=False)
    op.create_index(op.f("ix_products_seller_id"), "products", ["seller_id"], unique=False)
    op.create_index(op.f("ix_products_status"), "products", ["status"], unique=False)
    op.create_table(
        "recipe_comments",
        sa.Column("recipe_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("parent_comment_id", sa.BigInteger(), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["parent_comment_id"], ["recipe_comments.id"], name=op.f("fk_recipe_comments_parent_comment_id_recipe_comments"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["recipe_id"], ["recipes.id"], name=op.f("fk_recipe_comments_recipe_id_recipes"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_recipe_comments_user_id_users"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recipe_comments")),
    )
    op.create_index(op.f("ix_recipe_comments_created_at"), "recipe_comments", ["created_at"], unique=False)
    op.create_index(op.f("ix_recipe_comments_is_deleted"), "recipe_comments", ["is_deleted"], unique=False)
    op.create_index(op.f("ix_recipe_comments_parent_comment_id"), "recipe_comments", ["parent_comment_id"], unique=False)
    op.create_index(op.f("ix_recipe_comments_recipe_id"), "recipe_comments", ["recipe_id"], unique=False)
    op.create_index(op.f("ix_recipe_comments_user_id"), "recipe_comments", ["user_id"], unique=False)
    op.create_table(
        "recipe_likes",
        sa.Column("recipe_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["recipe_id"], ["recipes.id"], name=op.f("fk_recipe_likes_recipe_id_recipes"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_recipe_likes_user_id_users"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recipe_likes")),
        sa.UniqueConstraint("recipe_id", "user_id", name="uq_recipe_likes_recipe_id_user_id"),
    )
    op.create_index(op.f("ix_recipe_likes_created_at"), "recipe_likes", ["created_at"], unique=False)
    op.create_index(op.f("ix_recipe_likes_recipe_id"), "recipe_likes", ["recipe_id"], unique=False)
    op.create_index(op.f("ix_recipe_likes_user_id"), "recipe_likes", ["user_id"], unique=False)
    op.create_table(
        "recipe_saves",
        sa.Column("recipe_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["recipe_id"], ["recipes.id"], name=op.f("fk_recipe_saves_recipe_id_recipes"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_recipe_saves_user_id_users"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recipe_saves")),
        sa.UniqueConstraint("recipe_id", "user_id", name="uq_recipe_saves_recipe_id_user_id"),
    )
    op.create_index(op.f("ix_recipe_saves_created_at"), "recipe_saves", ["created_at"], unique=False)
    op.create_index(op.f("ix_recipe_saves_recipe_id"), "recipe_saves", ["recipe_id"], unique=False)
    op.create_index(op.f("ix_recipe_saves_user_id"), "recipe_saves", ["user_id"], unique=False)
    op.create_table(
        "seller_contacts",
        sa.Column("seller_id", sa.BigInteger(), nullable=False),
        sa.Column("phone_hash", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=128), nullable=True),
        sa.Column("matched_user_id", sa.BigInteger(), nullable=True),
        sa.Column("status", sa.Enum("PENDING", "INVITED", "JOINED", "DECLINED", name="contact_import_status", native_enum=False, length=16), server_default="pending", nullable=False),
        sa.Column("last_invited_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("invite_token", sa.String(length=48), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["matched_user_id"], ["users.id"], name=op.f("fk_seller_contacts_matched_user_id_users"), ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["seller_id"], ["seller_profiles.id"], name=op.f("fk_seller_contacts_seller_id_seller_profiles"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_seller_contacts")),
        sa.UniqueConstraint("seller_id", "phone_hash", name="uq_seller_contacts_seller_id_phone_hash"),
    )
    op.create_index(op.f("ix_seller_contacts_created_at"), "seller_contacts", ["created_at"], unique=False)
    op.create_index(op.f("ix_seller_contacts_invite_token"), "seller_contacts", ["invite_token"], unique=False)
    op.create_index(op.f("ix_seller_contacts_matched_user_id"), "seller_contacts", ["matched_user_id"], unique=False)
    op.create_index(op.f("ix_seller_contacts_phone_hash"), "seller_contacts", ["phone_hash"], unique=False)
    op.create_index(op.f("ix_seller_contacts_seller_id"), "seller_contacts", ["seller_id"], unique=False)
    op.create_table(
        "seller_groups",
        sa.Column("seller_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("avatar_url", sa.String(length=512), nullable=True),
        sa.Column("privacy", sa.Enum("PUBLIC", "PRIVATE", "INVITE_ONLY", name="seller_group_privacy", native_enum=False, length=20), server_default="invite_only", nullable=False),
        sa.Column("invite_slug", sa.String(length=48), nullable=False),
        sa.Column("members_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["seller_id"], ["seller_profiles.id"], name=op.f("fk_seller_groups_seller_id_seller_profiles"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_seller_groups")),
    )
    op.create_index(op.f("ix_seller_groups_created_at"), "seller_groups", ["created_at"], unique=False)
    op.create_index(op.f("ix_seller_groups_invite_slug"), "seller_groups", ["invite_slug"], unique=True)
    op.create_index(op.f("ix_seller_groups_is_deleted"), "seller_groups", ["is_deleted"], unique=False)
    op.create_index(op.f("ix_seller_groups_seller_id"), "seller_groups", ["seller_id"], unique=False)
    op.create_table(
        "broadcasts",
        sa.Column("seller_id", sa.BigInteger(), nullable=False),
        sa.Column("target_type", sa.Enum("FOLLOWERS", "GROUP", "CITY", "REPEAT_BUYERS", "ALL_MY_CUSTOMERS", name="broadcast_target_type", native_enum=False, length=32), nullable=False),
        sa.Column("target_ref", sa.String(length=64), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("media", sa.JSON(), nullable=False),
        sa.Column("cta_type", sa.Enum("OPEN_PRODUCT", "OPEN_SELLER", "ORDER_NOW", "EXTERNAL_URL", "NONE", name="broadcast_cta", native_enum=False, length=20), server_default="none", nullable=False),
        sa.Column("cta_product_id", sa.BigInteger(), nullable=True),
        sa.Column("cta_url", sa.String(length=512), nullable=True),
        sa.Column("status", sa.Enum("DRAFT", "QUEUED", "SENDING", "SENT", "CANCELLED", "FAILED", name="broadcast_status", native_enum=False, length=16), server_default="draft", nullable=False),
        sa.Column("scheduled_for", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("audience_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("delivered_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("failed_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("clicked_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("converted_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["cta_product_id"], ["products.id"], name=op.f("fk_broadcasts_cta_product_id_products"), ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["seller_id"], ["seller_profiles.id"], name=op.f("fk_broadcasts_seller_id_seller_profiles"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_broadcasts")),
    )
    op.create_index(op.f("ix_broadcasts_created_at"), "broadcasts", ["created_at"], unique=False)
    op.create_index(op.f("ix_broadcasts_scheduled_for"), "broadcasts", ["scheduled_for"], unique=False)
    op.create_index(op.f("ix_broadcasts_seller_id"), "broadcasts", ["seller_id"], unique=False)
    op.create_index(op.f("ix_broadcasts_status"), "broadcasts", ["status"], unique=False)
    op.create_table(
        "channel_posts",
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("channel_id", sa.BigInteger(), nullable=False),
        sa.Column("message_id", sa.BigInteger(), nullable=False),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_edited_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("views_cached", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], name=op.f("fk_channel_posts_product_id_products"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_channel_posts")),
        sa.UniqueConstraint("channel_id", "message_id", name="uq_channel_posts_channel_id_message_id"),
    )
    op.create_index(op.f("ix_channel_posts_created_at"), "channel_posts", ["created_at"], unique=False)
    op.create_index(op.f("ix_channel_posts_product_id"), "channel_posts", ["product_id"], unique=False)
    op.create_table(
        "community_posts",
        sa.Column("author_id", sa.BigInteger(), nullable=False),
        sa.Column("city_id", sa.BigInteger(), nullable=True),
        sa.Column("product_id", sa.BigInteger(), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("photos", sa.JSON(), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("likes_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("comments_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], name=op.f("fk_community_posts_author_id_users"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["city_id"], ["citys.id"], name=op.f("fk_community_posts_city_id_citys"), ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], name=op.f("fk_community_posts_product_id_products"), ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_community_posts")),
    )
    op.create_index(op.f("ix_community_posts_author_id"), "community_posts", ["author_id"], unique=False)
    op.create_index(op.f("ix_community_posts_city_id"), "community_posts", ["city_id"], unique=False)
    op.create_index(op.f("ix_community_posts_created_at"), "community_posts", ["created_at"], unique=False)
    op.create_index(op.f("ix_community_posts_is_deleted"), "community_posts", ["is_deleted"], unique=False)
    op.create_index(op.f("ix_community_posts_product_id"), "community_posts", ["product_id"], unique=False)
    op.create_table(
        "product_photos",
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("url", sa.String(length=512), nullable=False),
        sa.Column("tg_file_id", sa.String(length=256), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], name=op.f("fk_product_photos_product_id_products"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_photos")),
    )
    op.create_index(op.f("ix_product_photos_created_at"), "product_photos", ["created_at"], unique=False)
    op.create_index(op.f("ix_product_photos_product_id"), "product_photos", ["product_id"], unique=False)
    op.create_table(
        "seller_group_members",
        sa.Column("group_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("source", sa.Enum("MANUAL", "INVITE", "IMPORTED", "OPT_IN_FROM_ORDER", name="group_member_source", native_enum=False, length=24), nullable=False),
        sa.Column("opt_in_marketing", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("opt_in_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("channels", sa.JSON(), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("muted_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["group_id"], ["seller_groups.id"], name=op.f("fk_seller_group_members_group_id_seller_groups"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_seller_group_members_user_id_users"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_seller_group_members")),
        sa.UniqueConstraint("group_id", "user_id", name="uq_seller_group_members_group_id_user_id"),
    )
    op.create_index(op.f("ix_seller_group_members_created_at"), "seller_group_members", ["created_at"], unique=False)
    op.create_index(op.f("ix_seller_group_members_group_id"), "seller_group_members", ["group_id"], unique=False)
    op.create_index(op.f("ix_seller_group_members_opt_in_marketing"), "seller_group_members", ["opt_in_marketing"], unique=False)
    op.create_index(op.f("ix_seller_group_members_user_id"), "seller_group_members", ["user_id"], unique=False)
    op.create_table(
        "storys",
        sa.Column("seller_id", sa.BigInteger(), nullable=False),
        sa.Column("media_url", sa.String(length=512), nullable=False),
        sa.Column("media_type", sa.String(length=16), nullable=False),
        sa.Column("tg_file_id", sa.String(length=256), nullable=True),
        sa.Column("caption", sa.String(length=512), nullable=True),
        sa.Column("product_id", sa.BigInteger(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_archived", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("views_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], name=op.f("fk_storys_product_id_products"), ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["seller_id"], ["seller_profiles.id"], name=op.f("fk_storys_seller_id_seller_profiles"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_storys")),
    )
    op.create_index(op.f("ix_storys_created_at"), "storys", ["created_at"], unique=False)
    op.create_index(op.f("ix_storys_expires_at"), "storys", ["expires_at"], unique=False)
    op.create_index(op.f("ix_storys_is_archived"), "storys", ["is_archived"], unique=False)
    op.create_index(op.f("ix_storys_seller_id"), "storys", ["seller_id"], unique=False)
    op.create_table(
        "broadcast_deliverys",
        sa.Column("broadcast_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.Enum("QUEUED", "SENDING", "DELIVERED", "READ", "CLICKED", "CONVERTED", "FAILED", "SKIPPED", name="broadcast_delivery_status", native_enum=False, length=16), server_default="queued", nullable=False),
        sa.Column("tg_chat_id", sa.BigInteger(), nullable=True),
        sa.Column("tg_message_id", sa.BigInteger(), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("clicked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("converted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.String(length=512), nullable=True),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["broadcast_id"], ["broadcasts.id"], name=op.f("fk_broadcast_deliverys_broadcast_id_broadcasts"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_broadcast_deliverys_user_id_users"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_broadcast_deliverys")),
        sa.UniqueConstraint("broadcast_id", "user_id", name="uq_broadcast_deliveries_broadcast_id_user_id"),
    )
    op.create_index("ix_broadcast_deliveries_b_status", "broadcast_deliverys", ["broadcast_id", "status"], unique=False)
    op.create_index(op.f("ix_broadcast_deliverys_broadcast_id"), "broadcast_deliverys", ["broadcast_id"], unique=False)
    op.create_index(op.f("ix_broadcast_deliverys_created_at"), "broadcast_deliverys", ["created_at"], unique=False)
    op.create_index(op.f("ix_broadcast_deliverys_status"), "broadcast_deliverys", ["status"], unique=False)
    op.create_index(op.f("ix_broadcast_deliverys_user_id"), "broadcast_deliverys", ["user_id"], unique=False)
    op.create_table(
        "orders",
        sa.Column("buyer_id", sa.BigInteger(), nullable=False),
        sa.Column("seller_id", sa.BigInteger(), nullable=False),
        sa.Column("subtotal_minor", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("delivery_fee_minor", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("discount_minor", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("total_minor", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("currency", sa.Enum("UZS", "USD", name="currency", native_enum=False, length=8), server_default="UZS", nullable=False),
        sa.Column("delivery_address", sa.Text(), nullable=True),
        sa.Column("delivery_city_id", sa.BigInteger(), nullable=True),
        sa.Column("delivery_lat", sa.Float(), nullable=True),
        sa.Column("delivery_lon", sa.Float(), nullable=True),
        sa.Column("scheduled_for", sa.DateTime(timezone=True), nullable=True),
        sa.Column("buyer_comment", sa.Text(), nullable=True),
        sa.Column("buyer_phone_e164", sa.String(length=20), nullable=True),
        sa.Column("status", sa.Enum("NEW", "ACCEPTED", "IN_PROGRESS", "READY", "OUT_FOR_DELIVERY", "DELIVERED", "CANCELLED", "REFUNDED", name="order_status", native_enum=False, length=20), server_default="new", nullable=False),
        sa.Column("cancelled_reason", sa.String(length=256), nullable=True),
        sa.Column("source_broadcast_id", sa.BigInteger(), nullable=True),
        sa.Column("source_channel_message_id", sa.BigInteger(), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["buyer_id"], ["users.id"], name=op.f("fk_orders_buyer_id_users"), ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["delivery_city_id"], ["citys.id"], name=op.f("fk_orders_delivery_city_id_citys"), ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["seller_id"], ["seller_profiles.id"], name=op.f("fk_orders_seller_id_seller_profiles"), ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["source_broadcast_id"], ["broadcasts.id"], name=op.f("fk_orders_source_broadcast_id_broadcasts"), ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
    )
    op.create_index(op.f("ix_orders_buyer_id"), "orders", ["buyer_id"], unique=False)
    op.create_index(op.f("ix_orders_created_at"), "orders", ["created_at"], unique=False)
    op.create_index(op.f("ix_orders_delivery_city_id"), "orders", ["delivery_city_id"], unique=False)
    op.create_index(op.f("ix_orders_seller_id"), "orders", ["seller_id"], unique=False)
    op.create_index(op.f("ix_orders_source_broadcast_id"), "orders", ["source_broadcast_id"], unique=False)
    op.create_index(op.f("ix_orders_status"), "orders", ["status"], unique=False)
    op.create_table(
        "post_comments",
        sa.Column("post_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("parent_comment_id", sa.BigInteger(), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["parent_comment_id"], ["post_comments.id"], name=op.f("fk_post_comments_parent_comment_id_post_comments"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["post_id"], ["community_posts.id"], name=op.f("fk_post_comments_post_id_community_posts"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_post_comments_user_id_users"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_post_comments")),
    )
    op.create_index(op.f("ix_post_comments_created_at"), "post_comments", ["created_at"], unique=False)
    op.create_index(op.f("ix_post_comments_is_deleted"), "post_comments", ["is_deleted"], unique=False)
    op.create_index(op.f("ix_post_comments_parent_comment_id"), "post_comments", ["parent_comment_id"], unique=False)
    op.create_index(op.f("ix_post_comments_post_id"), "post_comments", ["post_id"], unique=False)
    op.create_index(op.f("ix_post_comments_user_id"), "post_comments", ["user_id"], unique=False)
    op.create_table(
        "post_likes",
        sa.Column("post_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["post_id"], ["community_posts.id"], name=op.f("fk_post_likes_post_id_community_posts"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_post_likes_user_id_users"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_post_likes")),
        sa.UniqueConstraint("post_id", "user_id", name="uq_post_likes_post_id_user_id"),
    )
    op.create_index(op.f("ix_post_likes_created_at"), "post_likes", ["created_at"], unique=False)
    op.create_index(op.f("ix_post_likes_post_id"), "post_likes", ["post_id"], unique=False)
    op.create_index(op.f("ix_post_likes_user_id"), "post_likes", ["user_id"], unique=False)
    op.create_table(
        "story_views",
        sa.Column("story_id", sa.BigInteger(), nullable=False),
        sa.Column("viewer_id", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["story_id"], ["storys.id"], name=op.f("fk_story_views_story_id_storys"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["viewer_id"], ["users.id"], name=op.f("fk_story_views_viewer_id_users"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_story_views")),
        sa.UniqueConstraint("story_id", "viewer_id", name="uq_story_views_story_id_viewer_id"),
    )
    op.create_index(op.f("ix_story_views_created_at"), "story_views", ["created_at"], unique=False)
    op.create_index(op.f("ix_story_views_story_id"), "story_views", ["story_id"], unique=False)
    op.create_index(op.f("ix_story_views_viewer_id"), "story_views", ["viewer_id"], unique=False)
    op.create_table(
        "order_items",
        sa.Column("order_id", sa.BigInteger(), nullable=False),
        sa.Column("product_id", sa.BigInteger(), nullable=True),
        sa.Column("title_snapshot", sa.String(length=200), nullable=False),
        sa.Column("unit_price_minor", sa.BigInteger(), nullable=False),
        sa.Column("qty", sa.Integer(), server_default="1", nullable=False),
        sa.Column("options_snapshot", sa.JSON(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], name=op.f("fk_order_items_order_id_orders"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], name=op.f("fk_order_items_product_id_products"), ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_items")),
    )
    op.create_index(op.f("ix_order_items_created_at"), "order_items", ["created_at"], unique=False)
    op.create_index(op.f("ix_order_items_order_id"), "order_items", ["order_id"], unique=False)
    op.create_table(
        "order_status_logs",
        sa.Column("order_id", sa.BigInteger(), nullable=False),
        sa.Column("from_status", sa.Enum("NEW", "ACCEPTED", "IN_PROGRESS", "READY", "OUT_FOR_DELIVERY", "DELIVERED", "CANCELLED", "REFUNDED", name="order_status", native_enum=False, length=20), nullable=True),
        sa.Column("to_status", sa.Enum("NEW", "ACCEPTED", "IN_PROGRESS", "READY", "OUT_FOR_DELIVERY", "DELIVERED", "CANCELLED", "REFUNDED", name="order_status", native_enum=False, length=20), nullable=False),
        sa.Column("actor_user_id", sa.BigInteger(), nullable=True),
        sa.Column("note", sa.String(length=512), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["actor_user_id"], ["users.id"], name=op.f("fk_order_status_logs_actor_user_id_users"), ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], name=op.f("fk_order_status_logs_order_id_orders"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_status_logs")),
    )
    op.create_index(op.f("ix_order_status_logs_created_at"), "order_status_logs", ["created_at"], unique=False)
    op.create_index(op.f("ix_order_status_logs_order_id"), "order_status_logs", ["order_id"], unique=False)
    op.create_table(
        "payments",
        sa.Column("order_id", sa.BigInteger(), nullable=False),
        sa.Column("provider", sa.Enum("PAYME", "CLICK", "CASH", name="payment_provider", native_enum=False, length=16), nullable=False),
        sa.Column("status", sa.Enum("PENDING", "AUTHORIZED", "PAID", "FAILED", "REFUNDED", "CANCELLED", name="payment_status", native_enum=False, length=16), server_default="pending", nullable=False),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.Enum("UZS", "USD", name="currency", native_enum=False, length=8), server_default="UZS", nullable=False),
        sa.Column("external_id", sa.String(length=128), nullable=True),
        sa.Column("checkout_url", sa.String(length=1024), nullable=True),
        sa.Column("failure_reason", sa.String(length=256), nullable=True),
        sa.Column("raw_payload", sa.JSON(), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], name=op.f("fk_payments_order_id_orders"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payments")),
    )
    op.create_index(op.f("ix_payments_created_at"), "payments", ["created_at"], unique=False)
    op.create_index(op.f("ix_payments_external_id"), "payments", ["external_id"], unique=False)
    op.create_index(op.f("ix_payments_order_id"), "payments", ["order_id"], unique=False)
    op.create_index(op.f("ix_payments_provider"), "payments", ["provider"], unique=False)
    op.create_index(op.f("ix_payments_status"), "payments", ["status"], unique=False)
    op.create_table(
        "reviews",
        sa.Column("order_id", sa.BigInteger(), nullable=False),
        sa.Column("seller_id", sa.BigInteger(), nullable=False),
        sa.Column("author_id", sa.BigInteger(), nullable=False),
        sa.Column("rating", sa.SmallInteger(), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("seller_reply", sa.Text(), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("rating >= 1 AND rating <= 5", name=op.f("ck_reviews_ck_reviews_rating_range")),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], name=op.f("fk_reviews_author_id_users"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], name=op.f("fk_reviews_order_id_orders"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["seller_id"], ["seller_profiles.id"], name=op.f("fk_reviews_seller_id_seller_profiles"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reviews")),
        sa.UniqueConstraint("order_id", name="uq_reviews_order_id"),
    )
    op.create_index(op.f("ix_reviews_author_id"), "reviews", ["author_id"], unique=False)
    op.create_index(op.f("ix_reviews_created_at"), "reviews", ["created_at"], unique=False)
    op.create_index(op.f("ix_reviews_is_deleted"), "reviews", ["is_deleted"], unique=False)
    op.create_index(op.f("ix_reviews_order_id"), "reviews", ["order_id"], unique=False)
    op.create_index(op.f("ix_reviews_seller_id"), "reviews", ["seller_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reviews_seller_id"), table_name="reviews")
    op.drop_index(op.f("ix_reviews_order_id"), table_name="reviews")
    op.drop_index(op.f("ix_reviews_is_deleted"), table_name="reviews")
    op.drop_index(op.f("ix_reviews_created_at"), table_name="reviews")
    op.drop_index(op.f("ix_reviews_author_id"), table_name="reviews")
    op.drop_table("reviews")
    op.drop_index(op.f("ix_payments_status"), table_name="payments")
    op.drop_index(op.f("ix_payments_provider"), table_name="payments")
    op.drop_index(op.f("ix_payments_order_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_external_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_created_at"), table_name="payments")
    op.drop_table("payments")
    op.drop_index(op.f("ix_order_status_logs_order_id"), table_name="order_status_logs")
    op.drop_index(op.f("ix_order_status_logs_created_at"), table_name="order_status_logs")
    op.drop_table("order_status_logs")
    op.drop_index(op.f("ix_order_items_order_id"), table_name="order_items")
    op.drop_index(op.f("ix_order_items_created_at"), table_name="order_items")
    op.drop_table("order_items")
    op.drop_index(op.f("ix_story_views_viewer_id"), table_name="story_views")
    op.drop_index(op.f("ix_story_views_story_id"), table_name="story_views")
    op.drop_index(op.f("ix_story_views_created_at"), table_name="story_views")
    op.drop_table("story_views")
    op.drop_index(op.f("ix_post_likes_user_id"), table_name="post_likes")
    op.drop_index(op.f("ix_post_likes_post_id"), table_name="post_likes")
    op.drop_index(op.f("ix_post_likes_created_at"), table_name="post_likes")
    op.drop_table("post_likes")
    op.drop_index(op.f("ix_post_comments_user_id"), table_name="post_comments")
    op.drop_index(op.f("ix_post_comments_post_id"), table_name="post_comments")
    op.drop_index(op.f("ix_post_comments_parent_comment_id"), table_name="post_comments")
    op.drop_index(op.f("ix_post_comments_is_deleted"), table_name="post_comments")
    op.drop_index(op.f("ix_post_comments_created_at"), table_name="post_comments")
    op.drop_table("post_comments")
    op.drop_index(op.f("ix_orders_status"), table_name="orders")
    op.drop_index(op.f("ix_orders_source_broadcast_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_seller_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_delivery_city_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_created_at"), table_name="orders")
    op.drop_index(op.f("ix_orders_buyer_id"), table_name="orders")
    op.drop_table("orders")
    op.drop_index(op.f("ix_broadcast_deliverys_user_id"), table_name="broadcast_deliverys")
    op.drop_index(op.f("ix_broadcast_deliverys_status"), table_name="broadcast_deliverys")
    op.drop_index(op.f("ix_broadcast_deliverys_created_at"), table_name="broadcast_deliverys")
    op.drop_index(op.f("ix_broadcast_deliverys_broadcast_id"), table_name="broadcast_deliverys")
    op.drop_index("ix_broadcast_deliveries_b_status", table_name="broadcast_deliverys")
    op.drop_table("broadcast_deliverys")
    op.drop_index(op.f("ix_storys_seller_id"), table_name="storys")
    op.drop_index(op.f("ix_storys_is_archived"), table_name="storys")
    op.drop_index(op.f("ix_storys_expires_at"), table_name="storys")
    op.drop_index(op.f("ix_storys_created_at"), table_name="storys")
    op.drop_table("storys")
    op.drop_index(op.f("ix_seller_group_members_user_id"), table_name="seller_group_members")
    op.drop_index(op.f("ix_seller_group_members_opt_in_marketing"), table_name="seller_group_members")
    op.drop_index(op.f("ix_seller_group_members_group_id"), table_name="seller_group_members")
    op.drop_index(op.f("ix_seller_group_members_created_at"), table_name="seller_group_members")
    op.drop_table("seller_group_members")
    op.drop_index(op.f("ix_product_photos_product_id"), table_name="product_photos")
    op.drop_index(op.f("ix_product_photos_created_at"), table_name="product_photos")
    op.drop_table("product_photos")
    op.drop_index(op.f("ix_community_posts_product_id"), table_name="community_posts")
    op.drop_index(op.f("ix_community_posts_is_deleted"), table_name="community_posts")
    op.drop_index(op.f("ix_community_posts_created_at"), table_name="community_posts")
    op.drop_index(op.f("ix_community_posts_city_id"), table_name="community_posts")
    op.drop_index(op.f("ix_community_posts_author_id"), table_name="community_posts")
    op.drop_table("community_posts")
    op.drop_index(op.f("ix_channel_posts_product_id"), table_name="channel_posts")
    op.drop_index(op.f("ix_channel_posts_created_at"), table_name="channel_posts")
    op.drop_table("channel_posts")
    op.drop_index(op.f("ix_broadcasts_status"), table_name="broadcasts")
    op.drop_index(op.f("ix_broadcasts_seller_id"), table_name="broadcasts")
    op.drop_index(op.f("ix_broadcasts_scheduled_for"), table_name="broadcasts")
    op.drop_index(op.f("ix_broadcasts_created_at"), table_name="broadcasts")
    op.drop_table("broadcasts")
    op.drop_index(op.f("ix_seller_groups_seller_id"), table_name="seller_groups")
    op.drop_index(op.f("ix_seller_groups_is_deleted"), table_name="seller_groups")
    op.drop_index(op.f("ix_seller_groups_invite_slug"), table_name="seller_groups")
    op.drop_index(op.f("ix_seller_groups_created_at"), table_name="seller_groups")
    op.drop_table("seller_groups")
    op.drop_index(op.f("ix_seller_contacts_seller_id"), table_name="seller_contacts")
    op.drop_index(op.f("ix_seller_contacts_phone_hash"), table_name="seller_contacts")
    op.drop_index(op.f("ix_seller_contacts_matched_user_id"), table_name="seller_contacts")
    op.drop_index(op.f("ix_seller_contacts_invite_token"), table_name="seller_contacts")
    op.drop_index(op.f("ix_seller_contacts_created_at"), table_name="seller_contacts")
    op.drop_table("seller_contacts")
    op.drop_index(op.f("ix_recipe_saves_user_id"), table_name="recipe_saves")
    op.drop_index(op.f("ix_recipe_saves_recipe_id"), table_name="recipe_saves")
    op.drop_index(op.f("ix_recipe_saves_created_at"), table_name="recipe_saves")
    op.drop_table("recipe_saves")
    op.drop_index(op.f("ix_recipe_likes_user_id"), table_name="recipe_likes")
    op.drop_index(op.f("ix_recipe_likes_recipe_id"), table_name="recipe_likes")
    op.drop_index(op.f("ix_recipe_likes_created_at"), table_name="recipe_likes")
    op.drop_table("recipe_likes")
    op.drop_index(op.f("ix_recipe_comments_user_id"), table_name="recipe_comments")
    op.drop_index(op.f("ix_recipe_comments_recipe_id"), table_name="recipe_comments")
    op.drop_index(op.f("ix_recipe_comments_parent_comment_id"), table_name="recipe_comments")
    op.drop_index(op.f("ix_recipe_comments_is_deleted"), table_name="recipe_comments")
    op.drop_index(op.f("ix_recipe_comments_created_at"), table_name="recipe_comments")
    op.drop_table("recipe_comments")
    op.drop_index(op.f("ix_products_status"), table_name="products")
    op.drop_index(op.f("ix_products_seller_id"), table_name="products")
    op.drop_index(op.f("ix_products_published_at"), table_name="products")
    op.drop_index(op.f("ix_products_is_deleted"), table_name="products")
    op.drop_index(op.f("ix_products_created_at"), table_name="products")
    op.drop_index("ix_products_city_status_pub", table_name="products")
    op.drop_index(op.f("ix_products_city_id"), table_name="products")
    op.drop_index(op.f("ix_products_category_id"), table_name="products")
    op.drop_index("ftx_products_title_desc", table_name="products", mysql_prefix="FULLTEXT")
    op.drop_table("products")
    op.drop_index(op.f("ix_follows_seller_id"), table_name="follows")
    op.drop_index(op.f("ix_follows_follower_id"), table_name="follows")
    op.drop_index(op.f("ix_follows_created_at"), table_name="follows")
    op.drop_table("follows")
    op.drop_index(op.f("ix_seller_profiles_verification"), table_name="seller_profiles")
    op.drop_index(op.f("ix_seller_profiles_user_id"), table_name="seller_profiles")
    op.drop_index(op.f("ix_seller_profiles_slug"), table_name="seller_profiles")
    op.drop_index(op.f("ix_seller_profiles_created_at"), table_name="seller_profiles")
    op.drop_index(op.f("ix_seller_profiles_city_id"), table_name="seller_profiles")
    op.drop_index(op.f("ix_seller_profiles_brand_name"), table_name="seller_profiles")
    op.drop_table("seller_profiles")
    op.drop_index("ix_recipes_pub_city", table_name="recipes")
    op.drop_index(op.f("ix_recipes_is_published"), table_name="recipes")
    op.drop_index(op.f("ix_recipes_is_deleted"), table_name="recipes")
    op.drop_index(op.f("ix_recipes_created_at"), table_name="recipes")
    op.drop_index(op.f("ix_recipes_city_id"), table_name="recipes")
    op.drop_index(op.f("ix_recipes_author_id"), table_name="recipes")
    op.drop_index("ftx_recipes_title_desc", table_name="recipes", mysql_prefix="FULLTEXT")
    op.drop_table("recipes")
    op.drop_index(op.f("ix_notifications_user_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_type"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_read_at"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_created_at"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(op.f("ix_users_tg_username"), table_name="users")
    op.drop_index(op.f("ix_users_tg_id"), table_name="users")
    op.drop_index(op.f("ix_users_role"), table_name="users")
    op.drop_index(op.f("ix_users_phone_hash"), table_name="users")
    op.drop_index(op.f("ix_users_is_deleted"), table_name="users")
    op.drop_index(op.f("ix_users_created_at"), table_name="users")
    op.drop_index(op.f("ix_users_city_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_citys_slug"), table_name="citys")
    op.drop_index(op.f("ix_citys_is_active"), table_name="citys")
    op.drop_index(op.f("ix_citys_created_at"), table_name="citys")
    op.drop_table("citys")
    op.drop_index(op.f("ix_categorys_slug"), table_name="categorys")
    op.drop_index(op.f("ix_categorys_parent_id"), table_name="categorys")
    op.drop_index(op.f("ix_categorys_is_active"), table_name="categorys")
    op.drop_index(op.f("ix_categorys_created_at"), table_name="categorys")
    op.drop_table("categorys")
    # ### end Alembic commands ###
